<?php

/**
 * PluginfpPaymentCustomerProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginfpPaymentCustomerProfileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginfpPaymentCustomerProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginfpPaymentCustomerProfile');
    }
}