<?php

/**
 * PluginfpPaymentCustomerProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    fpPayment
 * @subpackage Base
 * @author     Ton Sharp <Forma-PRO@66ton99.org.ua>
 */
abstract class PluginfpPaymentCustomerProfile extends BasefpPaymentCustomerProfile
{

  /**
   * (non-PHPdoc)
   * @see Doctrine_Record::save()
   */
  public function save(Doctrine_Connection $conn = null)
  {
    parent::save($conn);
    if (ProfileTypeEnum::DEF == $this->getType()) {
      $list = $this->getTable()
        ->createQuery('p')
        ->andWhere('p.type = ?', ProfileTypeEnum::DEF)
        ->andWhere('p.id != ?', $this->getId())
        ->execute();
      foreach ($list as $profile) {
        $profile->setType(ProfileTypeEnum::SHIPPING);
        $profile->save();
      }
    }
  }
}