<?php

/**
 * PluginfpPaymentOrderItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    fpPayment
 * @subpackage Base
 * @author     Ton Sharp <Forma-PRO@66ton99.org.ua>
 */
abstract class PluginfpPaymentOrderItem extends BasefpPaymentOrderItem
{
}