all:
  context_class_name: 'fpPaymentContext'
  payments_context_prefix: 'fpPayment'
  cart_item_holder_callback: 'fpPaymentCartContext::getInstance'
  customer_model_name: 'sfGuardUser'
  price_manager_class: 'fpPaymentPriceManager'
  currency: 'USD'
  customer_callback:
    function: 'sfContext::getInstance'
    parameters: []
    subFunctions: ['getUser', 'getGuardUser']
  object_classe_name: 'Product' 
  checkout_first_step: '@fpPaymentPlugin_method'
  checkout_billing_step: '@fpPaymentPlugin_billing'
  payment_method_class_form: 'fpPaymentMethodPluginForm'
  select_profile_class_form: 'fpPaymentSelectProfileForm'
  order_class_form: 'fpPaymentOrderReviewForm'
  main_ns: 'fpPaymentNS'
  profiles_ns: 'fpPaymentCurrentProfiles'
  product_extra_fields: # it aren't dynamyc fields
#    photo:
#      name: photo
#      alias: null
#      type: string
#      length: null
#      options:
#        notnull: true
    description:
      name: description
      alias: null
      type: string
      length: null
      options: 
        notnull: true
 