all:
  payments_context_prefix: 'fpPayment'
  login_strict_mode: <?php echo sfConfig::get('fp_payment_cart_login_strict_mode', true) . "\n" ?> 
  payment_method_class_form: 'fpPaymentMethodPluginForm'
  cart_item_holder_callback: 'fpPaymentCartContext::getInstance'
  customer_model_name: 'sfGuardUser'
  customer_callback:
    function: 'sfContext::getInstance'
    parameters: []
    subFunctions: ['getUser', 'getGuardUser']
  object_classe_name: <?php echo sfConfig::get('fp_payment_cart_object_classe_name', 'product') ?> 
  checkout_first_step: '@fpPaymentPlugin_method'
  checkout_billing_step: '@fpPaymentPlugin_billing'
  select_profile_class_form: 'fpPaymentSelectProfileForm'
  product_extra_fields: # it aren't dynamyc fields
#    photo:
#      name: photo
#      alias: null
#      type: string
#      length: null
#      options:
#        notnull: true
    description:
      name: description
      alias: null
      type: string
      length: null
      options: 
        notnull: true
 