all:
  payments_context_prefix: 'fpPayment'
  login_strict_mode: <?php echo sfConfig::get('fp_payment_cart_login_strict_mode', true) . "\n" ?> 
  class_form_payment_method: 'fpPaymentMethodPluginForm'
  callback_cart_item_holder: 'fpPaymentCartContext::getInstance'
  callback_user:
    function: 'sfContext::getInstance'
    parameters: []
    subFunctions: ['getUser', 'getGuardUser']
  object_classes_names: <?php echo sfConfig::get('fp_payment_cart_object_classes_names', 'product') ?> 
  product_extra_fields: # it aren't dynamyc fields
#    photo:
#      name: photo
#      alias: null
#      type: string
#      length: null
#      options:
#        notnull: true
    description:
      name: description
      alias: null
      type: string
      length: null
      options: 
        notnull: true
 