fpPaymentPlugin_cart:
  url:   /cart
  param: { module: fpPaymentCart, action: show }

fpPaymentPlugin_checkout:
  url:   /checkout
  param: { module: fpPaymentCheckout, action: index }

fpPaymentPlugin_billing:
  url:   /checkout/billing
  param: { module: fpPaymentCheckout, action: billing }
  
fpPaymentPlugin_profile:
  url:   /checkout/profile
  param: { module: fpPaymentCheckout, action: profile }
  
fpPaymentPlugin_shipping:
  url:   /checkout/shipping
  param: { module: fpPaymentCheckout, action: shipping }

fpPaymentPlugin_method:
  url:   /checkout/method
  param: { module: fpPaymentCheckout, action: method }

fpPaymentPlugin_info:
  url:   /checkout/payment
  param: { module: fpPaymentCheckout, action: info }
  
fpPaymentPlugin_shippingMethod:
  url:   /checkout/shippingMethod
  param: { module: fpPaymentCheckout, action: shippingMethod }

fpPaymentPlugin_orderReview:
  url:   /checkout/orderReview
  param: { module: fpPaymentCheckout, action: orderReview }

  
fpPaymentPlugin_error:
  url:   /checkout/error
  param: { module: fpPaymentCheckout, action: error }

fpPaymentPlugin_success:
  url:   /checkout/success
  param: { module: fpPaymentCheckout, action: success }
  
fpPaymentPlugin_orderStatus:
  url:   /order/status/:id
  param: { module: fpPayment, action: orderStatus }

  
