fpPaymentPlugin_cart:
  url:   /cart
  param: { module: fpPaymentCart, action: show }

fpPaymentPlugin_checkout:
  url:   /checkout
  param: { module: fpPaymentCheckout, action: index }

fpPaymentPlugin_billing:
  url:   /checkout/billing
  param: { module: fpPaymentCheckout, action: billing }
  
fpPaymentPlugin_profile:
  url:   /checkout/profile
  param: { module: fpPaymentCheckout, action: profile }
  
fpPaymentPlugin_shipping:
  url:   /checkout/shipping
  param: { module: fpPaymentCheckout, action: shipping }

fpPaymentPlugin_method:
  url:   /checkout/method
  param: { module: fpPaymentCheckout, action: method }

fpPaymentPlugin_info:
  url:   /checkout/payment/:method
  param: { module: fpPaymentCheckout, action: info }
  
fpPaymentPlugin_order:
  url:   /checkout/order
  param: { module: fpPaymentCheckout, action: order }
  
fpPaymentPlugin_error:
  url:   /checkout/error/:method
  param: { module: fpPaymentCheckout, action: error }

fpPaymentPlugin_success:
  url:   /checkout/success/:method
  param: { module: fpPaymentCheckout, action: success }
  

  
