fpPaymentPlugin_checkout_payment_methods:
  url:   /checkout
  param: { module: fpPaymentCheckout, action: index }

#fpPaymentPlugin_order:
#  url:   /checkout/order
#  param: { module: fpPaymentCheckout, action: order }
  
fpPaymentPlugin_info:
  url:   /checkout/info/:method
  param: { module: fpPaymentCheckout, action: info }
  
fpPaymentPlugin_error:
  url:   /checkout/error/:method
  param: { module: fpPaymentCheckout, action: error }

fpPaymentPlugin_success:
  url:   /checkout/success/:method
  param: { module: fpPaymentCheckout, action: success }
  
fpPaymentPlugin_cart:
  url:   /cart
  param: { module: fpPaymentCart, action: show }