fpPaymentOrder:
  actAs:
    Timestampable: ~
  columns:
    customer_id: {type: integer, notnull: true}
    status: {type: enum, values: [<?php echo fpPaymentOrderStatusEnum::implode() ?>] }
    type: {type: varchar(255)}
    currency: {type: varchar(6), notnull: true}
  relations:
    Customer:
      class: sfGuardUser
      local:    customer_id
      onDelete: CASCADE

fpPaymentOrderItem:
  actAs:
    Timestampable: ~
  columns:
    oreder_id: {type: integer, notnull: true}
    object_id: {type: integer}
    quantity: {type: integer, notnull: tru}
    name: {type: varchar(255)}
    price: {type: decimal(10), scale: 2, notnull: true}
  relations:
    Order:
      class: fpPaymentOrder
      local: oreder_id
      onDelete: CASCADE
    Product:
      class: <?php sfConfig::get('fp_payment_object_classes_names', 'product') ?>
      local: object_id
      onDelete: CASCADE